#!/bin/bash

if [ ! -d /backup ]
  then
    mkdir /backup
fi
DATE=$(date +"%Y%m%d%H%M")
DBFILE=/backup/${DBNAME}_${DATE}.dump
TARFILE=/backup/${DBNAME}_${DATE}.tar

PWD=$"odoo"
export PGPASSWORD=$PWD
echo "Backup of database..."
pg_dump -Fc -U odoo -h db -f ${DBFILE} $DBNAME
if [ $? -ne 0 ]
  then
    echo "Error! DB Backup failed!"
    exit 2
fi
echo "Database saved"

echo "Backup of files..."
tar -cvf ${TARFILE} /home/odoo
if [ $? -ne 0 ]
  then 
    echo "Error! File backup failed!"
    exit 2
fi
echo "Files saved"
echo "Backup finished"
