#!/bin/bash
#########################################################################################

DATE=$(date +"%Y%m%d%H%M")
FDATE=$(date +"%d/%m/%Y %H:%M")
DBFILE=/backup/${DBNAME}_${DATE}.dump
TARFILE=/backup/${DBNAME}_${DATE}.tar

export PGPASSWORD="odoo"
pg_dump -Fc -U odoo -h db -f ${DBFILE} $DBNAME
if [ $? -ne 0 ]
  then
    echo $FDATE" Error! DB Backup failed!"
    exit 2
fi
echo $FDATE" DB Backup done"

tar -cf ${TARFILE} /var/lib/odoo
if [ $? -ne 0 ]
  then 
    echo $FDATE"Error! File backup failed!"
    exit 2
fi
echo $FDATE" Files saved"
