#!/bin/bash

DATE=$(date +"%Y%m%d%H%M")
DBFILE=/backup/${DBNAME}_${DATE}.dump
TARFILE=/backup/${DBNAME}_${DATE}.tar

export PGPASSWORD="odoo"
#echo "Backup of database... pg_dump -Fc -U ${conf[db_user]} -h ${conf[db_host]} -f ${DBFILE} $DBNAME"

#pg_dump -Fc -U ${conf[db_user]} -h ${conf[db_host]} -f ${DBFILE} $DBNAME
#echo "Backup pg_dump -Fc -U odoo -h db -f ${DBFILE} $DBNAME"
pg_dump -Fc -U odoo -h db -f ${DBFILE} $DBNAME
if [ $? -ne 0 ]
  then
    echo "Error! DB Backup failed!"
    exit 2
fi
echo "Database saved"

echo "Backup of files..."
tar -cvf ${TARFILE} /var/lib/odoo
if [ $? -ne 0 ]
  then 
    echo "Error! File backup failed!"
    exit 2
fi
echo "Files saved"

echo "Backup finished"
