#!/bin/bash
set -x
readonly RED="\e[31m"
readonly YELLOW="\e[33m"
readonly GREEN="\e[32m"
readonly STD="\e[0m"

if [ $# -lt 3 ]
  then
    echo -e "${RED}Error! Too few arguments supplied!${STD}"
    echo -e "${STD}Command: host-restore <customer> <db> <timestamp>"
    exit 1
fi

CUSTOMER=$1
DB=$2
DATE=$3

docker run --rm -ti \
       --volumes-from $CUSTOMER \
       -v /home/ubuntu/80/backup:/backup \
       --env DBNAME=$DB \
       --env DATE=$DATE \
       jobiols/backup \
       host-restore &> /home/ubuntu/$CUSTOMER.restore.log
