#!/bin/bash
set -x
readonly RED="\e[31m"
readonly YELLOW="\e[33m"
readonly GREEN="\e[32m"
readonly STD="\e[0m"

if [ $# -lt 3 ]
  then
    echo -e "${RED}Error! Too few arguments supplied!${STD}"
    echo -e "${STD}Command: jd-restore <customer> <db> <timestamp>"
    exit 1
fi

CUSTOMER=$1
DB=$2
DATE=$3

docker run \
       -ti \
       --volumes-from $CUSTOMER.data \
       -v /jamoshared/backup:/backup \
       --rm \
       --env DBNAME=$DB \
       --env DATE=$DATE \
       jamotion/odoo-backup \
       jamo-restore &> /jamoshared/backup/$CUSTOMER.restore.log
