#!/bin/bash

if [ ! -d /backup ]
  then
    echo "Error! /backup directory not found!"
    exit 2
fi

DBFILE=/backup/${DBNAME}_${DATE}.dump
TARFILE=/backup/${DBNAME}_${DATE}.tar

if [ ! -f ${TARFILE} ]
  then
    echo "Error! File ${TARFILE} not found!"
    exit 2
fi

if [ ! -f ${DBFILE} ]
  then
    echo "Error! File ${DBFILE} not found!"
    exit 2
fi

echo "Restore files..."
tar -xvf ${TARFILE} -C / --exclude='odoo.conf' --exclude 'odoo-dev.conf' --exclude 'odoo-debug.conf'
if [ $? -ne 0 ]
  then
    echo "Error! Restore of files failed!"
    exit 2
fi
echo "Files restored"

#PWD=${conf[db_password]}
export PGPASSWORD="odoo"
#echo "Drop database..."
#dropdb -U ${conf[db_user]} -h ${conf[db_host]} ${DBNAME}
#dropdb -U odoo -h db ${DBNAME}

echo "create new database ${NEW_DBNAME}"
createdb -U odoo -h db -T template0 ${NEW_DBNAME}

echo "restore to new created database"
pg_restore -U odoo -h db -d ${NEW_DBNAME} ${DBFILE}

#echo "Restore of database..."
#pg_restore -Fc -O -U ${conf[db_user]} -h ${conf[db_host]} -d ${DBNAME} ${DBFILE}
#pg_restore -U odoo -h db -d template1 -c -C ${DBFILE}

if [ $? -ne 0 ]
  then
    echo "Error! DB restore failed!"
    exit 2
fi
echo "Restore finished"
