#!/bin/bash
if [ ! -f /etc/odoo/openerp-server.conf ]
  then
    echo "Error! odoo.conf not found!"
    exit 2
fi

declare -A conf

IFS="="
while read -r name value
do
  key=$(echo "$name" | sed 's/^ *//g' | sed 's/ *$//g')
  val=$(echo "$value" | sed 's/^ *//g' | sed 's/ *$//g')
  conf[$key]=$val
done < /etc/odoo/openerp-server.conf

if [ ! -d /backup ]
  then
    echo "Error! /backup directory not found!"
    exit 2
fi

DBFILE=/backup/${DBNAME}_${DATE}.dump
TARFILE=/backup/${DBNAME}_${DATE}.tar

if [ ! -f ${TARFILE} ]
  then
    echo "Error! File ${TARFILE} not found!"
    exit 2
fi

if [ ! -f ${DBFILE} ]
  then
    echo "Error! File ${DBFILE} not found!"
    exit 2
fi

echo "Restore files..."
tar -xvf ${TARFILE} -C / --exclude='odoo.conf' --exclude 'odoo-dev.conf' --exclude 'odoo-debug.conf'
if [ $? -ne 0 ]
  then
    echo "Error! Restore of files failed!"
    exit 2
fi
echo "Files restored"

PWD=${conf[db_password]}
export PGPASSWORD=$PWD
echo "Restore of database..."
#pg_restore -Fc -O -U ${conf[db_user]} -h ${conf[db_host]} -d ${DBNAME} ${DBFILE}
pg_restore -U ${conf[db_user]} -h ${conf[db_host]} -d template1 -c -C ${DBFILE}

if [ $? -ne 0 ]
  then
    echo "Error! DB restore failed!"
    exit 2
fi
echo "Database restored"
echo "Restore finished"
